package com.industryprojectFrancescaLundvall.industryprojectfrancescalundvall.exception;

public class StaffNotFoundException extends Exception {
    // These are autogenerated error messages which are thrown by fetchStaffById()

    public StaffNotFoundException() {
        super();
    }

    public StaffNotFoundException(String message) {
        super(message);
    }

    public StaffNotFoundException(String message, Throwable cause) {
        super(message, cause);
    }

    public StaffNotFoundException(Throwable cause) {
        super(cause);
    }

    protected StaffNotFoundException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }
}
